# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking', '~> 3.0'
  pod 'SSZipArchive', '~> 1.2'
  pod 'FileManager'
  pod 'FileBrowser'
  pod 'Aspects'
  pod 'JSPatch'
  pod 'SocketRocket'
  pod 'Socket.IO-Client-Swift'

end
